const books = [
    {
        title: 'Becoming: Michelle Obama',
        author: 'Michelle Obama',
        genre:'biographies',
        pages: 400,
        booksWeLove: true,
        finished: true,
    },
    {
        title: 'Eu sei por que o pássaro canta na gaiola',
        author: 'Maya Angelou',
        genre:'biographies',
        pages: 336,
        booksWeLove: true,
        finished: true,
    },
    {
        title: 'Longa Caminhada até a Liberdade',
        author: 'Nelson Mandela',
        genre:'biographies',
        pages: 782,
        booksWeLove: null,
        finished: false, 
    },
    {
        title: 'Uma terra prometida',
        author: 'Barack Obama',
        genre:'biographies',
        pages: 764,
        booksWeLove: null,
        finished: false,
    },
    {
        title: 'Design Like You Give a Damn',
        author: 'Architecture for Humanity',
        genre:'education',
        pages: 333,
        booksWeLove: true,
        finished: true,
    },
    {
        title: 'JavaScript – O Guia Definitivo',
        author: 'David Flanagan',
        genre:'education',
        pages: 1080,
        booksWeLove: true,
        finished: false,
    },
    {
        title: 'Mindset: A nova psicologia do sucesso',
        author: 'Carol S. Dweck',
        genre:'education',
        pages: 312,
        booksWeLove: null ,
        finished: false ,
    },
    {
        title: '1984',
        author: 'George Orwell',
        genre:'fiction',
        pages: 336,
        booksWeLove: true,
        finished: true,
    },
    {
        title: 'A insustentável leveza do ser',
        author: 'Milan Kundera',
        genre:'fiction',
        pages: 344,
        booksWeLove: true,
        finished: true,
    },
    {
        title: 'Primeiro eu tive que morrer',
        author: 'Lorena Portela',
        genre:'fiction',
        pages: 140,
        booksWeLove: null,
        finished: false,
    },
    {
        title: 'Lying',
        author: 'Sam Harris',
        genre:'mental health',
        pages: 105,
        booksWeLove:true ,
        finished:true,
    },
    {
        title: 'Mulheres que correm com os lobos',
        author: 'Clarissa Pinkola Estés',
        genre:'mental health',
        pages: 576,
        booksWeLove: true,
        finished: true,
    },
    {
        title: 'O Demonio Do Meio Dia: Uma anatomia da depressão',
        author: 'Andrew Solomon',
        genre:'mental health',
        pages: 584,
        booksWeLove: true,
        finished: true,
    },
    {
        title: 'O Inferno Somos Nós',
        author: 'Monja Coen',
        genre:'mental health',
        pages: 112,
        booksWeLove: null,
        finished: true,
    }
];

module.exports = books;